name: guerresD_Antan
version: 0.1
main: gda2.Main
authors: [ZettaX, Inivican]
description: For Project Olympic
depend: [Vault] 
commands:
   gda:
      description: Main fucking command.
      usage: Oops! something went wrong... try /gda help :)
      permission: gda.main
      permission-message: For some reason, you are not allowed to use this command.