version: 0.1
name: CombatTagPlusPlus
main: zetta.Main
author: ZettaX
description: CombatTaggingForFlansMod
permissions:
    combatplusplus.Tagged:
        description: Tagged by combattagplusplus
    cbtplusplus.immune:
        description: Provides immunity from tagging/being tagged