version: 0.1
name: guerresD_Antan
main: zetta.Main
authors: [ZettaX, Inivican]
description: For Project Olympic
commands:
  test:
    usage: Well, you probably fucked up. It is not likely for this to stop working anyways
    description: Testing purposes
